name = "Alyscia"
author = "Dia"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2efea926780b0c2f00729b06a31186bea354239b6857ef1f4dae7cc920c27d72"

[versions]
fabric = "0.15.0"
minecraft = "1.20.1"
